export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Hussain",
  },
  { id: 2, profilePicture: "assets/person/2.jpeg", username: "Umar" },
  { id: 3, profilePicture: "assets/person/3.jpeg", username: "Wajahat" },
  { id: 4, profilePicture: "assets/person/4.jpeg", username: "Zarar" },
  { id: 5, profilePicture: "assets/person/5.jpeg", username: "Mehmood" },
  { id: 6, profilePicture: "assets/person/6.jpeg", username: "yahya" },
  { id: 7, profilePicture: "assets/person/7.jpeg", username: "Zaroon" },
];
export const Posts = [
  {
    id: 1,
    desc: "Group Photo of Alkhidmat members",
    photo: "assets/post/5.jpeg",
    date: "1 mins ago",
    userId: 1,
    like: 14,
    comment: 4,
  },
  {
    id: 2,
    desc: "Group photo of students of AlKHidmat school",
    photo: "assets/post/11.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 12,
    comment: 45,
  },
  {
    id: 3,
    desc: "Meeting with minister of work and development GB ",
    photo: "assets/post/1.jpeg",
    date: "9 mins ago",
    userId: 3,
    like: 87,
    comment: 23,
  },
  {
    id: 4,
    desc: "Free Medical Camp at Shatpa valley",
    photo: "assets/post/10.jpeg",
    date: "9 mins ago",
    userId: 4,
    like: 9,
    comment: 4,
  },
  {
    id: 5,
    desc: "Free Medical camp at Ghasing velley",
    photo: "assets/post/8.jpeg",
    date: "1 mins ago",
    userId: 5,
    like: 14,
    comment: 4,
  },
  {
    id: 6,
    desc: "BOOOOOOOM!!!!!! (That’s the sound of this waterfall)",
    photo: "assets/post/2.jpeg",
    date: "1 mins ago",
    userId: 6,
    like: 34,
    comment: 7,
  },
];
